In [1]:
import pandas as pd

data=pd.read_csv("C:/Users/shn20/Desktop/작업물/통계분석학회/주제 분석/전처리/kbl_2021_플오_선수_1차전처리.csv",encoding='CP949')
data.columns

Index(['Unnamed: 0', 'Date', 'team', 'Home/Away', 'entry', 'player_num',
       'name', 'Min', 'Pts', '2PT', '3PT', 'FG', 'FT', 'OR', 'DR', 'TOT', 'DK',
       'AST', 'TO', 'Stl', 'BS', 'PF', 'FO', 'PP'],
      dtype='object')

In [2]:
del data['Unnamed: 0']
#del data['V1']
#del data['V1.1']
del data['FG']
del data['TOT']
del data["DK"]
del data["Pts"]
data.columns

Index(['Date', 'team', 'Home/Away', 'entry', 'player_num', 'name', 'Min',
       '2PT', '3PT', 'FT', 'OR', 'DR', 'AST', 'TO', 'Stl', 'BS', 'PF', 'FO',
       'PP'],
      dtype='object')

In [3]:
data['m']=data['Min'].str.split(':').str[0]
data['s']=data['Min'].str.split(':').str[1]
#data.columns

In [4]:
data['2PT성공']=data['2PT'].str.split('/').str[0]
data['2PT시도']=data['2PT'].str.split('/').str[1]
data['3PT성공']=data['3PT'].str.split('/').str[0]
data['3PT시도']=data['3PT'].str.split('/').str[1]
data['FT성공']=data['FT'].str.split('/').str[0]
data['FT시도']=data['FT'].str.split('/').str[1]
del data['2PT']
del data['3PT']
del data['FT']

In [5]:
data.to_csv("kbl_2021_플오_선수_전처리_2차.csv",index=False)
pd.read_csv("kbl_2021_플오_선수_전처리_2차.csv")

,Date,team,Home/Away,entry,player_num,name,Min,OR,DR,AST,...,FO,PP,m,s,2PT성공,2PT시도,3PT성공,3PT시도,FT성공,FT시도
0,2021.04.10,고양 오리온 오리온스,Home,선발,21,김강선,24:12:00,2,1,0,...,0,1,24,12,1,1,0,2,0,0
1,2021.04.10,고양 오리온 오리온스,Home,선발,11,허일영,22:06,1,3,1,...,2,1,22,6,2,5,0,1,1,3
2,2021.04.10,고양 오리온 오리온스,Home,벤치,8,최현민,6:56,0,0,0,...,1,0,6,56,0,2,0,1,0,0
3,2021.04.10,고양 오리온 오리온스,Home,벤치,3,임종일,9:07,1,0,0,...,1,0,9,7,0,2,0,0,0,0
4,2021.04.10,고양 오리온 오리온스,Home,선발,43,이대성,24:32:00,0,3,2,...,4,0,24,32,0,7,3,7,4,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
451,2021.05.09,전주 KCC 이지스,Away,벤치,1,유병훈,0:00,0,0,0,...,0,0,0,0,0,0,0,0,0,0
452,2021.05.09,전주 KCC 이지스,Away,선발,2,송교창,33:11:00,2,2,0,...,3,6,33,11,8,13,2,7,0,1
453,2021.05.09,전주 KCC 이지스,Away,벤치,31,이진욱,0:26,0,0,0,...,0,0,0,26,1,1,0,0,0,0
454,2021.05.09,전주 KCC 이지스,Away,선발,5,유현준,36:47:00,1,2,6,...,1,1,36,47,2,5,0,2,0,0
455,2021.05.09,전주 KCC 이지스,Away,벤치,23,조 알렉산더,0:00,0,0,0,...,0,0,0,0,0,0,0,0,0,0